linters:
  enable:
    - gocognit
    - revive
    - goimports
    - gocognit
    - unconvert
    - unparam
    - gosec
    - unconvert
linters-settings:
  gocognit:
    min-complexity: 17

issues:
  exclude:
    - "exported (type|method|function|var) (.+) should have comment or be unexported"
    - "exported const (.+) should have comment (.+) or be unexported"
    - "package-comments: should have a package comment"
    - "S1016: should convert (.+) instead of using struct literal"
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - gocognit
