name: Pull Request Check Up

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/SPS-Redigan
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21.5'
    - run: go version
    - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.1
        args: --concurrency 4 --print-issued-lines=false --exclude-use-default=false --fix --timeout=15m
        skip-cache: true

    - name: Unit Test
      run: CGO_ENABLED=1 go test $(go list ./... | grep -v /mocks/) -gcflags=all=-l --race -v -short -coverprofile=profile.cov

    - name: Test Goverage Threshold
      run: |
        totalCoverage=$(go tool cover -func profile.cov | awk '/total:/ {print substr($3, 1, length($3)-1)}')

        if [ $(echo "$totalCoverage >= 0" | bc -l) -eq 1 ]
        then
            echo "Test Coverage: $totalCoverage% [PASSED]\n"
        else
            echo "Test Coverage: $totalCoverage% [BELOW THRESHOLD]\n"
            exit 1
        fi

    - name: Build
      run: go build -v ./...
